title: "[announcements] "
labels: ["Ask the community for help"]
body:
  - type: markdown
    attributes:
      value: |
        ### Describe the issue
  - type: textarea
    id: issue
    attributes:
      label: Description of the issue
      description: "A clear and concise description of what the issue is."
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### EBSD map information        
  - type: textarea
    id: mapDescription
    attributes:
      label: Description of the sample
      description: "A clear and concise description of the sample condition."
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true         
  - type: dropdown
    id: fileType
    attributes:
      label: Map type
      options:
        - ctf
        - cpr and crc
        - h5oina
        - ang
        - osc
        - txt
    validations:
      required: true
  - type: dropdown
    id: mapType
    attributes:
      label: Grid type
      options:
        - Square
        - Hexagonal
    validations:
      required: true
