clear all; close all;

% Create some random data
xData = sort(rand(20,1)*50);
yData = rand(20,1)*50;

%% Call the plotMarker function
% Note: Run each command sequentially

% plotMarker(xData,yData,...
% 'lineStyle', '--', 'lineColor', [1 0 0], 'lineWidth',2,...
% 'marker','e',...
% 'innerMarker',...
% 'markerEdgeColor',[0 0 0],...
% 'markerFaceColor',[0 1 1],...
% 'markerSize',5);

plotMarker(xData,yData,...
'lineStyle', '-.', 'lineColor', [1 0 1], 'lineWidth',2,...
'marker','^',...
'markerStep',180*degree,...
'markerEdgeColor',[0 0 1],...
'markerFaceColor',[0.5 0.75 0.25],...
'markerSize',3);
%%


